
export class HeaderConstant{

  static readonly TITLE_FONT_SIZE_PLUS: number = 4;

  static readonly TITLE_FONT_WEIGHT: number = 500;

  static readonly LETTER_SPACING: number = 2;

  static readonly Z_INDEX: number = 2;

  static readonly SYSCAP_ETHERNET: string = 'SystemCapability.Multimedia.Audio.Device';

  static readonly AUDIO_DEVICE_SERVICE: string = '音频设备管理';

  static readonly TOAST_DURATION: number = 2000;
}