

export class PlayerConstant{
  /**
   * The font size of the singer is smaller.
   */
  static readonly FONT_REDUCE: number = 4;

  /**
   * The layout weight of player control.
   */
  static readonly LAYOUT_WEIGHT_PLAYER_CONTROL: number = 1;

  /**
   * The display priority is 1.
   */
  static readonly DISPLAY_PRIORITY_ONE: number = 1;

  /**
   * The display priority is 2.
   */
  static readonly DISPLAY_PRIORITY_TWO: number = 2;

  /**
   * The display priority is 3.
   */
  static readonly DISPLAY_PRIORITY_THREE: number = 3;

  /**
   * The rotate is 360.
   */
  static readonly ROTATE: number = 360;

  /**
   * The animation duration is 3000.
   */
  static readonly ANIMATION_DURATION: number = 3000;

  /**
   * The value of iterations.
   */
  static readonly ITERATIONS: number = -1;

  /**
   * The value of font weight.
   */
  static readonly FONT_WEIGHT_700: number = 700;

  /**
   * The value of font weight.
   */
  static readonly FONT_WEIGHT_500: number = 500;

  /**
   * The value of font family.
   */
  static readonly FONT_FAMILY_BLACK: string = 'HarmonyHeiTi';

  /**
   * The value of font family.
   */
  static readonly FONT_FAMILY_BOLD: string = 'HarmonyHeiTi-Bold';

  /**
   * The value of font family.
   */
  static readonly FONT_FAMILY_MEDIUM: string = 'HarmonyHeiTi-Medium';

  /**
   * The value of encoding.
   */
  static readonly ENCODING: string = 'utf-8';

  /**
   * The value of back ground image width and height.
   */
  static readonly BACK_IMAGE: string = '120%';

  /**
   * Set the image blur level.
   */
  static readonly IMAGE_BLUR: number = 150;

}