

export class SongConstant{

  static readonly ADD_INDEX_ONE: number = 1;

  static readonly ADD_INDEX_TWO: number = 2;

  static readonly ADD_INDEX_THREE: number = 3;

  static readonly SLICE_START_ZERO: number = 0;

  static readonly SLICE_END_THREE: number = 3;

  static readonly SLICE_INDEX_ONE: number = 1;

  static readonly SLICE_INDEX_TWO: number = 2;

  static readonly SLICE_INDEX_FOUR: number = 4;

  static readonly ID_NO_EXIT: number = 16501001;

  static readonly TRANSITION_DURATION: number = 500;
}